CREATE TABLE [TABELA DE PRODUTOS]
(
[CODIGO DO PRODUTO] VARCHAR (20) NOT NULL,
[NOME DO PRODUTO] VARCHAR (150),
[TAMANHO] CHAR (1),
[COR] VARCHAR (50),
[PRECO DE LISTA] SMALLMONEY
);

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO]);

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],[TAMANHO],[COR],[PRECO DE LISTA])
VALUES
('1040107','Anel Turquesa','P','Azul Turquesa',250.00);

SELECT * FROM [TABELA DE PRODUTOS]

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('1040108', 'Anel Turquesa','P','Azul Turquesa',250.00),
('1040109', 'Anel Turquesa','M','Azul Turquesa',250.00),
('1040110', 'Anel Turquesa','G','Azul Turquesa',250.00),
('1088126', 'Anel de prata tipo Boho', 'M', 'Prata', 352.25),
('1088127', 'Anel de prata tipo Boho', 'P', 'Prata', 352.25),
('1088128', 'Anel de prata tipo Boho', 'G', 'Prata', 352.25),
('1088799', 'Anel Rubi', 'M', 'Vermelho', 452.68),
('1088798', 'Anel Rubi', 'G', 'Vermelho', 452.68),
('1088800', 'Anel Rubi', 'P', 'Vermelho', 452.68)

UPDATE [TABELA DE PRODUTOS]
SET [TAMANHO] = 'G', [PRECO DE LISTA] = 283.00
WHERE [CODIGO DO PRODUTO] = '1040107';

SELECT * FROM [TABELA DE PRODUTOS]

DELETE [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1040110'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO]= 'Anel Turquesa'


--UPDATE [TABELA DE PRODUTOS]
--SET [PREÇO DE LISTA] = 250.00 * 1.1
--WHERE[CODIGO DO PRODUTO] = 1040108   Para fazer a alteração de percentual com somente um código

UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 1.1
WHERE [NOME DO PRODUTO] = 'Anel Turquesa'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE[PRECO DE LISTA] = 275.00

SELECT * FROM [TABELA DE PRODUTOS]
WHERE[PRECO DE LISTA] > 275.00

SELECT * FROM [TABELA DE PRODUTOS]
WHERE[PRECO DE LISTA] >= 275.00

SELECT * FROM [TABELA DE PRODUTOS]
WHERE[PRECO DE LISTA] <= 275.00

SELECT * FROM [TABELA DE PRODUTOS]
WHERE[PRECO DE LISTA] <> 275.00

SELECT * FROM [TABELA DE PRODUTOS]
WHERE[COR] >='Prata'
